services:
  - type: web
    name: agripulse-web
    runtime: docker
    plan: free
    autoDeployTrigger: commit
    healthCheckPath: /actuator/health/liveness
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
